name: Pull request continuous integration
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  proof:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anishathalye/proof-html@v1
        with:
          directory: ./
          check_opengraph: false
          tokens: |
            {"https://github.com": "${{ secrets.GITHUB_TOKEN }}"}
          url_ignore: |
            https://www.data.ai/en/resources/gamechangers/
